baseURL = "https://rosshemsley.co.uk/"
languageCode = "en-uk"
SectionPagesMenu = "main"
title = "Ross Hemsley"

theme = "ananke"
googleAnalytics = "UA-40455296-1"
ignorefiles = [ "content/drafts/.*" ]
publishDir = "../docs"
enableGitInfo = true
pygmentsStyle = "monokai"

[taxonomies]
   tag = "tags"
   category = "categories"

[params]
  AuthorName = "Ross Hemsley"
  gitHubUser = "rosshemsley"
  favicon = ""
  description = "Personal site for Ross Hemsley"
  instagram = ""
  github = "https://github.com/rosshemsley"
  linkedin = "https://www.linkedin.com/in/rosshemsley/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  featured_image = "header.jpg"
  recent_posts_number = 10