baseURL = "https://rosshemsley.co.uk/"
languageCode = "en-uk"
SectionPagesMenu = "main"
title = "Ross Hemsley"
theme = "ananke"

ignorefiles = [ "content/drafts/.*" ]

[params]
  favicon = ""
  description = "Personal site for Ross Hemsley"
  instagram = ""
  github = "https://github.com/rosshemsley"
  linkedin = "https://www.linkedin.com/in/rosshemsley/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  featured_image = "header.jpg"
  recent_posts_number = 2